
full_name = input("Fullname: ")
Student_id = input("Student ID: ")
department = input("Department: ")
year = int(input("Year: "))
university = input("University: ")
phone = int(input("Phone: "))

print("   AKIBA STUDENT CARD   ")
print(f"Name: {full_name}")
print(f"ID: {Student_id}")
print(f"Department: {department}")
print(f"Year: {year}")
print(f"University: {university}")
print(f"Phone: {phone}")
