full_name = input("Full name: ")
age = int(input("Age: "))
city = input("City: ")
university = input("University: ")
department = input("Department: ")
language = input("Favorite programming language: ")
goal = input("One programming goal: ")

print("    Student Information   ")
print(f"Name: {full_name}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"University: {university}")
print(f"Department: {department}")
print(f"Language: {language}")
print(f"Goal: {goal}")
