full_name = input("Full Name: ")
age = int(input("Age: "))
student_id = input("Student ID: ")
city = input("City: ")
university = input("University: ")
department = input("Department: ")
email = input("Email: ")
phone_number = input("Phone Number: ")
favorite_language = input("Favorite Programming Language: ")
programming_goal = input("Programming Goal: ")

width = 60

print("=" * width)
print("AKIBA STUDENT PROFILE".center(width))
print("=" * width)
print()
print(f"Name: {full_name}")
print(f"Student ID: {student_id}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"University: {university}")
print(f"Department: {department}")
print(f"Email: {email}")
print(f"Phone: {phone_number}")
print(f"Favorite Programming Language: {favorite_language}")
print()
print("Programming Goal")
print(f"{programming_goal}")
print("=" * width)
